sales_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: POVMATA-IZ40650
      user: talel
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      database: SALES_PIPELINE
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 1
      client_session_keep_alive: False

